## CON ESTE SIMBOLO # SE REALIZAN COMENTARIOS DE UNA SOLA LINEA EN EL CODIGO, ESTOS NO SON LEIDOS POR EL INTERPRETE DE PYTHON

"""
CON ESTE Comentarios.py SIMBOLO (TRES COMMILLAS DOBLES) SE REALIZAN
COMENTARIOS DE MULTIPLES LINEAS EN EL CODIGO, ESTOS NO SON LEIDOS POR EL INTERPRETE DE PYTHON"""

